# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python application


on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  STAGE: local

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv sync --dev
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          pipenv run flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          pipenv run flake8 app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          pipenv run black app --check
          pipenv run isort --check-only app
      - name: Test with mypy
        run: |
          pipenv run mypy --check-untyped-defs -p app

      - name: Start containers
        run: |
          docker-compose -f docker-compose-ci-testing up -d
          docker-compose ps
      - name: Test with pytest
        run: |
          pipenv run pytest
